// Package fixtureauth is a DEVELOPMENT_ONLY Verifier: opaque bearer tokens
// mapped to principals in a local JSON file generated by deploy/dev/up.sh.
// It stands in for the real IdP protocol until ENV-07 supplies the issuer,
// audience and introspection inputs (A12: go-oidc + x/oauth2); it must never
// be enabled outside a development profile.
package fixtureauth

import (
	"context"
	"crypto/subtle"
	"encoding/json"
	"fmt"
	"os"

	"github.com/ancyloce/anvilkit-agent-api/internal/application"
)

type entry struct {
	TenantID  string   `json:"tenantId"`
	ProjectID string   `json:"projectId"`
	ActorID   string   `json:"actorId"`
	Roles     []string `json:"roles"`
}

type Verifier struct{ tokens map[string]entry }

func Load(path string) (*Verifier, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("fixtureauth: %w", err)
	}
	var tokens map[string]entry
	if err := json.Unmarshal(raw, &tokens); err != nil {
		return nil, fmt.Errorf("fixtureauth: %w", err)
	}
	for tok, e := range tokens {
		if len(tok) < 16 || e.TenantID == "" || e.ActorID == "" {
			return nil, fmt.Errorf("fixtureauth: token entries need >=16 chars, tenantId and actorId")
		}
	}
	return &Verifier{tokens: tokens}, nil
}

func (v *Verifier) Verify(_ context.Context, bearer string) (application.Principal, error) {
	for tok, e := range v.tokens {
		if subtle.ConstantTimeCompare([]byte(tok), []byte(bearer)) == 1 {
			return application.Principal{TenantID: e.TenantID, ProjectID: e.ProjectID, ActorID: e.ActorID, Roles: e.Roles}, nil
		}
	}
	return application.Principal{}, application.ErrUnauthenticated
}
